<a href="https://colab.research.google.com/github/Daksh-Raghuvanshi/Machine-Learnig-Projects/blob/main/Random_Forest_Regressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here we gonna use Random Forest Regressor to predict the values of House in Bangalore House Price dataset.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor

In [ ]:
df = pd.read_csv('/content/bangalore house price prediction OHE-data (1).csv')
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [ ]:
X = df.drop('price' , axis = 1)
y = df['price']

In [ ]:
print(X.shape)
print(y.shape)

(7120, 107)
(7120,)


In [ ]:
X_train , X_test , y_train , y_test = train_test_split( X , y , test_size= 0.2 , random_state = 51)
print(f"{X_train.shape} ,{X_test.shape} , {y_train.shape} , {y_test.shape} ")

(5696, 107) ,(1424, 107) , (5696,) , (1424,) 


In [ ]:
sc = StandardScaler()
sc.fit(X_train)
print(sc.mean_)
print(sc.scale_)

[2.38307584e+00 1.57567977e+00 1.46585984e+03 2.45646067e+00
 5.91633522e+03 7.51404494e-01 1.82584270e-01 6.07443820e-02
 7.93539326e-01 3.26544944e-02 2.61587079e-02 2.12429775e-02
 1.66783708e-02 1.61516854e-02 1.56250000e-02 1.52738764e-02
 1.65028090e-02 1.50983146e-02 1.42205056e-02 1.31671348e-02
 1.19382022e-02 1.17626404e-02 1.12359551e-02 1.24648876e-02
 8.60252809e-03 7.37359551e-03 7.90028090e-03 8.07584270e-03
 7.54915730e-03 8.07584270e-03 7.54915730e-03 6.67134831e-03
 6.67134831e-03 5.79353933e-03 5.61797753e-03 6.49578652e-03
 5.44241573e-03 6.32022472e-03 5.09129213e-03 5.61797753e-03
 4.56460674e-03 6.49578652e-03 5.09129213e-03 6.14466292e-03
 5.61797753e-03 6.14466292e-03 4.21348315e-03 5.61797753e-03
 4.74016854e-03 5.61797753e-03 4.74016854e-03 4.91573034e-03
 5.26685393e-03 4.91573034e-03 4.03792135e-03 3.86235955e-03
 3.86235955e-03 4.38904494e-03 4.21348315e-03 3.51123596e-03
 3.68679775e-03 4.38904494e-03 4.38904494e-03 3.86235955e-03
 4.03792135e-03 3.511235

In [ ]:
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

Formation of the model 

In [ ]:
rfr_sqe = RandomForestRegressor(n_estimators =  100, criterion = "squared_error")
rfr_sqe.fit(X_train , y_train)
rfr_sqe.score(X_test , y_test)

0.8921807949462384

In [ ]:
rfr_abe = RandomForestRegressor(n_estimators =  100, criterion = "absolute_error")
rfr_abe.fit(X_train , y_train)
rfr_abe.score(X_test , y_test)

0.8684103047367424

In [ ]:
rfr_sqe.predict([X_test.iloc[-1,:]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([177.23])

In [ ]:
y_test.iloc[-1]

180.0

In [ ]:
rfr_sqe.predict(X_test)

array([ 79.5434,  39.9284, 119.61  , ...,  33.1812,  63.1684, 177.23  ])

In [ ]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

# Lets see how to save our basic Machine Learning model

In [ ]:
import joblib

In [ ]:
joblib.dump(rfr_sqe , 'Model_RFR')

['Model_RFR']

In [ ]:
model_loaded = joblib.load('Model_RFR')

In [ ]:
model_loaded.predict(X_test)


array([ 79.5434,  39.9284, 119.61  , ...,  33.1812,  63.1684, 177.23  ])

We can save our model by using Pickle also

In [ ]:
import pickle

In [ ]:
pickle.dump(rfr_sqe , open('model_pickle' , 'wb'))

In [ ]:
model_loaded_pickle = pickle.load(open('model_pickle' , 'rb'))

In [ ]:
model_loaded_pickle.predict(X_test[-1:])

array([177.23])

In [ ]:
np.array(X_test[-1:])

array([[2.00000000e+00, 0.00000000e+00, 1.56600000e+03, 2.00000000e+00,
        1.14942529e+04, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.000000