<a href="https://colab.research.google.com/github/Daksh-Raghuvanshi/Machine-Learnig-Projects/blob/main/Support_Vector_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Here we are gonna work on project based on SVC that is Breast Cancer Detection and will be delployi:ng it later

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import recall_score

In [ ]:
pd.set_option('display.max_columns' , None)

In [ ]:
data = load_breast_cancer()

In [ ]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
df = pd.DataFrame(np.c_[data.data, data.target] , columns = [list(data.feature_names) + ['target']])
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension radius error texture error perimeter error  \
0                0.07871       1.0950        0.9053           8.589   
1                0.05667       0.5435        0.7339           3.398   
2                0.05999       0.7456        0.7869           4.585   
3                0.09744       0.4956        1.1560           3.445   
4                0.05883       0.7572        0.7813           5.438   

  area error smoothness error compactness error concavity error  \
0     153.40         0.006399           0.04904         0.05373   
1      74.08         0.005225           0.01308         0.01860   
2      94.03         0.006150           0.04006         0.03832   
3      27.23         0.009110           0.07458         0.05661   
4      94.44         0.011490           0.02461         0.05688   

  concave points error symmetry error fractal dimension error worst radius  \
0              0.01587        0.03003                0.006193        25.38   
1              0.01340        0.01389                0.003532        24.99   
2              0.02058        0.02250                0.004571        23.57   
3              0.01867        0.05963                0.009208        14.91   
4              0.01885        0.01756                0.005115        22.54   

  worst texture worst perimeter worst area worst smoothness worst compactness  \
0         17.33          184.60     2019.0           0.1622            0.6656   
1         23.41          158.80     1956.0           0.1238            0.1866   
2         25.53          152.50     1709.0           0.1444            0.4245   
3         26.50           98.87      567.7           0.2098            0.8663   
4         16.67          152.20     1575.0           0.1374            0.2050   

  worst concavity worst concave points worst symmetry worst fractal dimension  \
0          0.7119               0.2654         0.4601                 0.11890   
1          0.2416               0.1860         0.2750                 0.08902   
2          0.4504               0.2430         0.3613                 0.08758   
3          0.6869               0.2575         0.6638                 0.17300   
4          0.4000               0.1625         0.2364                 0.07678   

  target  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0

In [ ]:
df.shape

(569, 31)

In [ ]:
# X = df.drop('target' , axis = 1)
# y = df['target']

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:4150: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


In [ ]:
X = df.iloc[: , 0:-1]
y = df.iloc[: , -1]

In [ ]:
X_train , X_test , y_train , y_test = train_test_split( X , y , test_size= 0.2 , random_state = 51)
print(f"{X_train.shape} ,{X_test.shape} , {y_train.shape} , {y_test.shape} ")

(455, 30) ,(114, 30) , (455,) , (114,) 


In [ ]:
y_test.head()

169    1.0
137    1.0
188    1.0
443    1.0
345    1.0
Name: (target,), dtype: float64

festure Scaling

In [ ]:
sc = StandardScaler()
sc.fit(X_train)
print(sc.mean_)
print(sc.scale_)

[1.41470967e+01 1.94833626e+01 9.21961099e+01 6.57439780e+02
 9.69954725e-02 1.07245626e-01 9.26326191e-02 5.03446659e-02
 1.82349011e-01 6.32115165e-02 4.18128352e-01 1.24280374e+00
 2.96717604e+00 4.17664286e+01 7.13407912e-03 2.65736088e-02
 3.35115815e-02 1.21546022e-02 2.10194484e-02 3.92049912e-03
 1.63035714e+01 2.58970549e+01 1.07628132e+02 8.84022857e+02
 1.32800615e-01 2.59909516e-01 2.80797582e-01 1.16446024e-01
 2.91661978e-01 8.45212088e-02]
[3.54999241e+00 4.28490844e+00 2.44819239e+01 3.53257254e+02
 1.45825736e-02 5.38700064e-02 8.10907160e-02 3.89378424e-02
 2.84083913e-02 7.41578359e-03 2.87019742e-01 5.60393480e-01
 2.11272475e+00 4.79004633e+01 3.09766785e-03 1.88405177e-02
 3.24732099e-02 6.47725842e-03 8.78080011e-03 2.82722945e-03
 4.80787310e+00 6.16164154e+00 3.35092238e+01 5.65240059e+02
 2.36065041e-02 1.59786053e-01 2.13343562e-01 6.61843255e-02
 6.35296361e-02 1.88147890e-02]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


In [ ]:
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


Model Training - SVC

In [ ]:
svc_rbf = SVC(kernel = 'rbf')
svc_rbf.fit(X_train_sc, y_train)
svc_rbf.score(X_test_sc , y_test)*100

94.73684210526315

In [ ]:
svc_linear = SVC(kernel = 'linear')
svc_linear.fit(X_train_sc, y_train)
svc_linear.score(X_test_sc , y_test)*100

94.73684210526315

In [ ]:
svc_poly = SVC(kernel = 'poly' , degree = 2)
svc_poly.fit(X_train_sc, y_train)
svc_poly.score(X_test_sc , y_test)*100

79.82456140350878

In [ ]:
y_pred_rbf = svc_rbf.predict(X_test_sc)
print(recall_score(y_test , y_pred_rbf))

1.0


In [ ]:
y_pred_linear= svc_linear.predict(X_test_sc)
print(recall_score(y_test , y_pred_linear))

1.0


Here we are choosing 'linear' as our kernel because the data is perfectly classified.

## Predict Cancer

In [ ]:
svc_linear.predict(X_test_sc)

array([1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
y_test

169    1.0
137    1.0
188    1.0
443    1.0
345    1.0
      ... 
538    1.0
123    1.0
224    1.0
115    1.0
425    1.0
Name: (target,), Length: 114, dtype: float64

## **Lets take a real life dataset to predict the cancer**

In [ ]:
patient_1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]
 

In [ ]:
patient_1sc = sc.transform(np.array([patient_1]))
patient_1sc

array([[ 1.08251028, -2.12451742,  1.25006067,  0.97254965,  1.46781549,
         3.16232325,  2.55846034,  2.48486634,  2.09624644,  2.08993201,
         2.35827558, -0.60226207,  2.66093534,  2.33053219, -0.23730082,
         1.19245085,  0.62261841,  0.57360654,  1.02616522,  0.80379075,
         1.88782615, -1.39038516,  2.29703524,  2.00795595,  1.24539341,
         2.53896053,  2.0206957 ,  2.25059294,  2.65132987,  1.82722173]])

In [ ]:
prediction = svc_linear.predict(patient_1sc)
prediction

array([0.])

In [ ]:
patient_1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]  
 

In [ ]:
if prediction[0] == 0:
  print("Malignant - The patient has Cancer")
else:
  print("Benign - The patient has NO Cancer")